/**
 * Tool definitions and schemas for the paper-search-agent MCP server.
 */

import type { AppConfig } from "../config.js";
import { enabledDiscoverySources, enabledRetrievalRoutes } from "../config.js";

// ── Shared Options schemas ──────────────────────────────────────────

const discoverySourcesSchema = (config: AppConfig) => ({
  type: "array",
  items: {
    type: "string",
    enum: enabledDiscoverySources(config),
  },
  description: "List of discovery sources to use. If omitted, uses all configured sources.",
});

// ── Tool Definitions ──────────────────────────────────────────────

export function getToolDefinitions(config: AppConfig) {
  const tools = [
    // ── Discovery Tools ──
    {
      name: "search_papers",
      description:
        "Search academic papers across multiple configured sources concurrently. " +
        "Merges and deduplicates results. Good for broad topic discovery.",
      inputSchema: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "Main search query (keywords, title, etc).",
          },
          advanced_query: {
            type: "string",
            description: "Optional advanced syntax query (if the source supports it, e.g. OpenAlex filters).",
          },
          limit: {
            type: "number",
            description: "Max results per source (default: 10, max: 50).",
          },
          year_range: {
            type: "object",
            properties: {
              start: { type: "number" },
              end: { type: "number" },
            },
            description: "Optional publication year filter.",
          },
          sources: discoverySourcesSchema(config),
        },
        required: ["query"],
      },
    },
    {
      name: "search_single_source",
      description:
        "Search academic papers using a specific discovery source. " +
        "Useful when you need source-specific features or want to retry a failed search.",
      inputSchema: {
        type: "object",
        properties: {
          source: {
            type: "string",
            enum: enabledDiscoverySources(config),
            description: "The source to query.",
          },
          query: {
            type: "string",
            description: "The search query.",
          },
          limit: {
            type: "number",
            description: "Max results (default: 20, max: 100).",
          },
          year_range: {
            type: "object",
            properties: {
              start: { type: "number" },
              end: { type: "number" },
            },
          },
        },
        required: ["source", "query"],
      },
    },

    // ── Planning Tools ──
    {
      name: "resolve_and_plan",
      description:
        "Resolve a paper's DOI and create a prioritized AccessPlan for full-text retrieval. " +
        "MUST be called before fetch_fulltext to determine the best access route.",
      inputSchema: {
        type: "object",
        properties: {
          doi: {
            type: "string",
            description: "The paper's DOI (e.g., '10.1038/s41586-020-2649-2').",
          },
        },
        required: ["doi"],
      },
    },
    {
      name: "check_local_cache",
      description:
        "Check if a paper's artifact is already in the local cache, avoiding network requests.",
      inputSchema: {
        type: "object",
        properties: {
          doi: {
            type: "string",
            description: "The paper's DOI.",
          },
        },
        required: ["doi"],
      },
    },

    // ── Retrieval Tools ──
    {
      name: "fetch_fulltext",
      description:
        "Execute an AccessPlan to retrieve the paper's full text. " +
        "Automatically tries fallback routes if the primary route fails. " +
        "Parses the retrieved artifact and returns structured content.",
      inputSchema: {
        type: "object",
        properties: {
          plan: {
            type: "object",
            description: "The AccessPlan object generated by resolve_and_plan.",
            // In a real schema we'd define the shape fully, but passing the raw object is fine for MCP
          },
        },
        required: ["plan"],
      },
    },
    {
      name: "import_local_file",
      description:
        "Import an existing local PDF, XML, or HTML file into the system cache " +
        "and parse it. Use this when the user has already downloaded the paper.",
      inputSchema: {
        type: "object",
        properties: {
          file_path: {
            type: "string",
            description: "Absolute or relative path to the local file.",
          },
          doi: {
            type: "string",
            description: "Optional DOI to associate with this file.",
          },
          title: {
            type: "string",
            description: "Optional title metadata.",
          },
        },
        required: ["file_path"],
      },
    },
    {
      name: "browser_retrieve",
      description:
        "Assisted browser retrieval. Opens a browser to the paper's URL " +
        "and attempts to extract the landing page or PDF. Pauses for user " +
        "intervention (CAPTCHA, login) if configured.",
      inputSchema: {
        type: "object",
        properties: {
          url: {
            type: "string",
            description: "URL to navigate to (usually the DOI resolver URL or publisher landing page).",
          },
          doi: {
            type: "string",
            description: "DOI of the paper being retrieved (for caching).",
          },
          action: {
            type: "string",
            enum: ["navigate", "check", "close"],
            description: "'navigate' to open/go to URL. 'check' to see if download completed. 'close' to clean up.",
          },
        },
        required: ["action"],
      },
    },

    // ── Parsing & Reading Tools ──
    {
      name: "parse_paper",
      description:
        "Parse a locally cached artifact (XML, HTML, Text) into a structured NormalizedPaperRecord. " +
        "Usually called automatically by fetch_fulltext, but useful for manual re-parsing.",
      inputSchema: {
        type: "object",
        properties: {
          file_path: {
            type: "string",
            description: "Path to the artifact file.",
          },
          artifact_type: {
            type: "string",
            enum: ["xml", "html", "pdf", "text"],
            description: "Type of the artifact. Auto-detected if omitted.",
          },
          paper_id: {
            type: "string",
            description: "ID to save the parsed record under (usually DOI or safe filename).",
          },
        },
        required: ["file_path", "paper_id"],
      },
    },
    {
      name: "get_paper_sections",
      description:
        "Retrieve specific text sections from a previously parsed paper. " +
        "Helps manage context window size by not loading the entire full text at once.",
      inputSchema: {
        type: "object",
        properties: {
          paper_id: {
            type: "string",
            description: "The ID of the parsed paper (usually DOI).",
          },
          sections: {
            type: "array",
            items: { type: "string" },
            description: "List of section names to retrieve (e.g., ['abstract', 'introduction', 'conclusion']).",
          },
        },
        required: ["paper_id", "sections"],
      },
    },

    // ── Storage & Corpus Tools ──
    {
      name: "manage_corpus",
      description:
        "Add, list, or remove papers from a named local corpus context. " +
        "Useful for grouping papers for a specific literature review.",
      inputSchema: {
        type: "object",
        properties: {
          action: {
            type: "string",
            enum: ["add", "remove", "list", "list_all"],
            description: "Action to perform on the corpus.",
          },
          corpus_name: {
            type: "string",
            description: "Name of the corpus (e.g., 'mcp-research').",
          },
          paper_id: {
            type: "string",
            description: "Required for 'add' and 'remove' actions.",
          },
          doi: {
            type: "string",
            description: "Optional DOI when adding.",
          },
          title: {
            type: "string",
            description: "Optional title when adding.",
          },
        },
        required: ["action"],
      },
    },
    {
      name: "export_records",
      description:
        "Export parsed papers or a corpus index to JSON, CSV, or BibTeX formats.",
      inputSchema: {
        type: "object",
        properties: {
          format: {
            type: "string",
            enum: ["json", "csv", "bibtex"],
          },
          corpus_name: {
            type: "string",
            description: "If provided, exports papers from this corpus. Otherwise exports all parsed papers.",
          },
          output_path: {
            type: "string",
            description: "Optional file path to write the output to.",
          },
        },
        required: ["format"],
      },
    },
  ];

  // ── Conditional Integrations ──
  if (config.integrations.zotero) {
    tools.push(
      {
        name: "zotero_lookup",
        description: "Search the configured Zotero library for a paper by DOI or title.",
        inputSchema: {
          type: "object",
          properties: {
            doi: { type: "string", description: "DOI to search for" },
            title: { type: "string", description: "Title to search for" },
            query: { type: "string", description: "General query" },
          },
        } as any,
      },
      {
        name: "zotero_save",
        description: "Save a paper to the configured Zotero library.",
        inputSchema: {
          type: "object",
          properties: {
            doi: { type: "string", description: "DOI to save" },
            title: { type: "string", description: "Title to save" },
            metadata: { type: "object", description: "Optional full metadata object." },
            collections: { type: "array", items: { type: "string" }, description: "Collection IDs." },
          },
        } as any,
      },
      {
        name: "zotero_list_collections",
        description: "List all collections in the configured Zotero library.",
        inputSchema: { type: "object", properties: {} } as any,
      }
    );
  }

  // Filter retrieval routes based on config
  const enabledRoutes = enabledRetrievalRoutes(config);
  if (!enabledRoutes.includes("browser_assisted")) {
    const idx = tools.findIndex((t) => t.name === "browser_retrieve");
    if (idx >= 0) tools.splice(idx, 1);
  }

  return tools;
}
